version: '3.1'

services:

  ghost:
    image: ghost:2.14.3
    restart: always
    depends_on: 
      - db
    ports:
      - 80:2368
    volumes: 
      - ./ghost/data:/var/lib/ghost/content
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      NODE_ENV: production
      url: http://ghost.local
      # server: 127.0.0.1:80
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__database: ghost

  db:
    image: mysql:5.7
    restart: always
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
