version: '3.7'

services:

  ghost:
    container_name: ghost
    image: ghost:2.19.3-alpine
    restart: always
    depends_on: 
      - mysql
    volumes: 
      - ./ghost/data:/var/lib/ghost/content
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      NODE_ENV: production
      url: http://ghost.local
      # server: 127.0.0.1:80
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD} # define mysql password in .env file
      database__connection__database: ghost

  nginx:
    container_name: nginx
    image: nginx:1.15.0-alpine
    restart: always
    volumes: 
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
      # - 443:443
      
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    restart: always
    volumes: 
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
